# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('plan', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_start', models.DateField()),
                ('travel_end', models.DateField()),
                ('user', models.ManyToManyField(related_name='user_trips', to='travel.User')),
            ],
        ),
    ]
