# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_trips', to='travel.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_travelers',
            field=models.ManyToManyField(related_name='travelers_trips', to='travel.User'),
        ),
    ]
